# Generated by Django 4.0.3 on 2023-07-19 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0002_shoe_color_shoe_manufacturer_shoe_picture_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_href', models.CharField(max_length=200, unique=True)),
                ('bin_name', models.CharField(max_length=200)),
                ('bin_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='shoe',
            name='bin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='shoes_rest.binvo'),
            preserve_default=False,
        ),
    ]
