# Generated by Django 4.0.3 on 2023-07-19 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0008_binvo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='binvo',
            old_name='bin_id',
            new_name='bin_number',
        ),
        migrations.RenameField(
            model_name='binvo',
            old_name='bin_name',
            new_name='closet_name',
        ),
        migrations.AddField(
            model_name='binvo',
            name='bin_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='bin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bin', to='shoes_rest.binvo'),
        ),
    ]
